### PR TITLE
Updade v2.2

### PR DESCRIPTION
**Pull request by LeandroStanger**

### CODE REVIEW

**Comment by nedrichards** [comment]
bot, build

**Comment by jurf** [comment]
This is going to be much more difficult than that. I’m leaving in a moment but I can do it tomorrow, I didn’t notice the update had already come out.

For one thing, you have a wrong checksum, and QtWebKit isn’t available in 5.10 yet, so we have to stick with 5.9. Also, the build fails when PortAudio is disabled because of [this](https://github.com/musescore/MuseScore/blame/master/mscore/seq.cpp#L54) – this should be reported upstream and/or patched. And it might be worth looking into whether it’s possible to disable the built-in Freetype and get nice rendering anyway yet.

Again, I can do this tomorrow, I’m just documenting it here so work isn’t duplicated pointlessly.

**Comment by jurf** [comment]
OK, this should now build, but it’ll fail, but I’ll fire it anyway so I can show it to the devs.

**Comment by jurf** [comment]
bot, build

**Comment by ericfont** [comment]
@jurf, if you want to build wihtout portmidi, maybe try with this commit https://github.com/musescore/MuseScore/pull/3592

But Ideally we (you and/or I) need to figure out how to build flatpak *with* portmidi, because one of the big features of 2.2 is that there is native midi output without using jack.  This native midi output uses portmidi.  I don't know much about how flatpak works, but when we made AppImage, it was a simple matter of making sure the build system installed portmidi library and that the library's .so was included in the AppImage.

**Comment by jurf** [comment]
bot, build

**Comment by jurf** [comment]
Ok, builds fine. I’ll merge this and open another issue for PortMidi.

**Pull request merged**
