### PR TITLE
Update to 3.6

### PR DESCRIPTION
**Pull request by kontomondo**

### CODE REVIEW

**Comment by hfiguiere** [comment]
MuseScore 3.6 is blocked from building on Qt 5.15.

This is why I haven't submitted it yet.

**Comment by hfiguiere** [comment]
The beta branch has the release candidate though.

**Comment by kontomondo** [comment]
@hfiguiere Thanks! Should I close the PR ?

**Comment by hfiguiere** [comment]
If you want to work on this, feel free.

One solution I see is to, sadly, downgrade to the 5.14 runtime, but this will cause some regressions.

**Comment by jurf** [comment]
Downgrading might be the way to go for now, unfortunately, since that’s upstream’s decision.

**Comment by hfiguiere** [comment]
That mean we can have JACK support anymore. :-(

**Comment by jurf** [comment]
Shucks. :-( Hard decision then. Maybe we could leave jack support in a separate branch? Hard to know whether more people want Jack or 3.6.

**Pull request closed without merging**
