### PR TITLE
Update to 4.0

### PR DESCRIPTION
**Pull request by hfiguiere**
added some packaging notes.

### CODE REVIEW

**Comment by adham-omran** [comment]
Works well but I am unable to find sounds downloaded by Muse Hub, is this a bug or something not supported at the moment?

**Comment by hfiguiere** [comment]
I have no idea how this works.

**Comment by adham-omran** [comment]
I don't too, I'm new to flatpaks in general, but for this case I know that Muse Hub stores the data in a directory (can be customized by the user) and MuseScore (Appimage) can read from it to get the sounds. Is there any reading I can do to help with this?

**Comment by hfiguiere** [comment]
So, not gonna support this. It's also probably build with an openSSL version that isn't available anymore. Like the crashpad binary that is in the tree.... (see the README in the repo).

The `network` permission already allow MuseScore to send data to website that don't have proper privacy rules (located outside of Europe). That's without analytics.

**Comment by hfiguiere** [comment]
BTW this is the beta build. I'll merge to stable later this week.

**Comment by hfiguiere** [comment]
And if you have specific issues about things not working with the flatpak, please file issues on this repository.

**Pull request merged**
