### PR TITLE
Beta: Provide the 3.5Beta release

### PR DESCRIPTION
**Pull request by hfiguiere**
- merged the `stable` branch to the `beta` branch and provide the 3.5alpha release.

### CODE REVIEW

**Comment by hfiguiere** [comment]
I'll rebase it with #56

**Comment by hfiguiere** [comment]
alpha2 is out.

**Comment by hfiguiere** [comment]
This is now 3.5 beta (for the beta branch). Changes also include allowing UPower dbus.

**Comment by jurf** [comment]
Why UPower?

**Comment by hfiguiere** [comment]
TBF I'm haven't figured out why it calls it `org.freedesktop.UPower.GetDisplayDevice`, but it does. I'm ok to remove this at that time until I understand. 

(without it there is an error about not accessing the system bus, and `--log-system-bus` shows it too)

**Comment by hfiguiere** [comment]
I removed UPower for now. I'll revisit this later.

**Pull request merged**
