### PR TITLE
Update AppData

### PR DESCRIPTION
**Pull request by jurf**
Add description (imported from the Windows store), release, translation,
copyright and launch info, screenshots, icons and URLs.

@nedrichards how does it look?

### CODE REVIEW

**Comment by jurf** [comment]
bot, build

**Comment by jurf** [comment]
bot, build

**Comment by nedrichards** [comment]
lgtm

**Comment by jurf** [comment]
Thanks.

**Comment by jurf** [comment]
Hm, GNOME Software still doesn’t show ‘Available in your language’, how can I fix that?

**Pull request merged**
