### PR TITLE
Update to 3.4.2 (Closes #51)

### LINKED ISSUE #51: MuseScore 3.4.1 Release
https://musescore.org/en/3.4.1

Thank you

### PR DESCRIPTION
**Pull request by hfiguiere**
This excludes changes from #49 but basically obsoletes and closes #48

### CODE REVIEW

**Comment by hfiguiere** [comment]
3.4.1 was released this morning. Updated the PR.

**Comment by hfiguiere** [comment]
I have another patch pending to disable in the build the telemetry module introduced in 3.4. (privacy)

**Comment by jurf** [comment]
Hey, thanks for the work! Why disable the telemetry however? I haven’t tried 3.4, but shouldn’t this be up to the user (if it’s configurable)? It doesn’t seem fair to the developers, and even to Flathub, since it would rule out Flatpak from the statistics.

**Comment by hfiguiere** [comment]
Telemetry = privacy issues.

On by default isn't fair to users.

**Comment by jurf** [comment]
It’s open-source software. I read the announcement; I don’t see any problems with privacy.

**Comment by hfiguiere** [comment]
open source isn't the golden hammer. Lot of things can be correlated on the backend. If you login to their system they know which IP is associate to your PII and can use that.

The processing of such data isn't open.

The best way to ensure data is private is to not have exfiltrated in the first place.

**Comment by hfiguiere** [comment]
3.4.2 is out. Updated the PR.

**Pull request merged**
