### PR TITLE
Bump SDK to 5.13

### LINKED ISSUE #39: Update runtime to 5.13

### PR DESCRIPTION
**Pull request by jurf**
Fixes #39.

### CODE REVIEW

**Comment by jurf** [comment]
Wait a sec, I didn’t want to bump the SDK, just Anki…

I mean, what.

**Comment by hfiguiere** [comment]
MuseScore doesn't build with 5.13 it seems. Needs work upstream.

**Comment by hfiguiere** [comment]
We are missing QtWegEngine in that SDK 5.13

**Comment by hfiguiere** [comment]
so we probably need flathub/io.qt.qtwebengine.BaseApp but it's not available in the repository

**Comment by jurf** [comment]
There was a discussion on IRC a while back, WebEngine should be a part of the SDK, but there were problems compiling it, so it was reverted (https://github.com/KDE/flatpak-kde-runtime/commit/fb5bbe40a1fc0406e101b1c9bfbe6262e0aa920d). Might be worth a try pinging the KDE folks – @aleixpol @grulja? What’s the status?

**Comment by grulja** [comment]
> There was a discussion on IRC a while back, WebEngine should be a part of the SDK, but there were problems compiling it, so it was reverted ([KDE/flatpak-kde-runtime@fb5bbe4](https://github.com/KDE/flatpak-kde-runtime/commit/fb5bbe40a1fc0406e101b1c9bfbe6262e0aa920d)). Might be worth a try pinging the KDE folks – @aleixpol @grulja? What’s the status?

QtWebEngine is now a base app, which means your up will end up building QtWebEngine.

See https://github.com/flathub/io.qt.qtwebengine.BaseApp.

The reason is we were unable to build it with Python2 due to some collision with Python3 in the Freedesktop runtime and this was the only solution we were able to do at this moment.

**Comment by hfiguiere** [comment]
The base app is NOT avaible on flathub. So it can't be used. I tried to get the an update on IRC about it... but so far I don't know.

**Comment by jurf** [comment]
The baseapp is available now, but I’ll probably leave this until after the 5.4 update.

**Comment by hfiguiere** [comment]
Yeah I made a branch for it over the week-end. It still had some issue. Including 
flathub/io.qt.qtwebengine.BaseApp#1 (I have a hackish solution for this, but there are other)

**Comment by jurf** [comment]
bot, build

**Comment by hfiguiere** [comment]
this PR won't build without change. You need to add QtWebEngine as a baseapp.

Also while it's happening, it should be 5.14 (unless there is a good reason not too)

**Comment by jurf** [comment]
Shoot, of course, this is what happens when you try to multi-task too much. I’d like to get this to finally compile, let’s try it.

**Comment by hfiguiere** [comment]
It needs a patch.

Like this:
https://github.com/hfiguiere/org.musescore.MuseScore/commit/7837937b7338ca07e645ee3cef144071c5e89199#diff-9c2473ca2881a222f70560c07a72066b

**Comment by hfiguiere** [comment]
And to run it it will need this:

https://github.com/hfiguiere/org.musescore.MuseScore/commit/0af7fcfce4cc0e65ed72b1c97968c3080b25911e

But even then, lots of errors on the console.

**Comment by hfiguiere** [comment]
That last patch might actually no longer be needed with https://github.com/flathub/io.qt.qtwebengine.BaseApp/pull/3

**Pull request closed without merging**
