### PR TITLE
Add PortMidi

### PR DESCRIPTION
**Pull request by jurf**
CC @ericfont. Could you please test the changes? I don’t have anything MIDI to test it with. Here’s a Flatpak [bundle](https://mega.nz/#!PEhXTaTJ!PslMYBXu0Z8_7_KNVzLCLOrHdVHtsWaud1No0GYCabo) to ease installation. 

Also, wow, is PortMidi a pain to build. And it doesn’t look like MuseScore actually uses `pm_defaults` so I removed it completely and don’t bundle the Java Runtime neither.

This PR includes some other changes, I find it pointless to divide the update into smaller parts.

### CODE REVIEW

**Comment by jurf** [comment]
bot, build

**Comment by ericfont** [comment]
Tried it and it works on my arch linux x86-64 machine.  Here's what I did:

Started an external midi synth (in this case QSynth)
sudo flatpak install musescore-portmidi.flatpak 
flatpak run org.musescore.MuseScore/x86_64/master
went to MuseScore Preferences I/O, and switched from PulseAudio to PortAudio
restarted musescore.
went to preferecnes again, and selected MIDI Output synth to be QSynth.
restarted musescore.
and now when I enter notes or play notes in musescore, QSynth receives and plays them.

BTW, I notice preferences doesn't have jack.  I'm guessing that is just the way things are?  But the good thing is you have portmidi working:

prefs

**Comment by ericfont** [comment]
oh, also I have a question, why does flatpak list show the 2.2 version to be labeled as "master".  Shouldn't it be called 2.2?

**Comment by ericfont** [comment]
Oh and regarding PmDefaults, you are correct MuseScore itself doesn't use PmDefaults.  PmDefaults is a stand-along application used to set preferences for MIDI input and output devices (and also just to test to make sure your midi devices work).

**Comment by jurf** [comment]
@ericfont: oh, that’s great news, I’ll merge this then. Thanks for the testing!

I’ve tried Jack but it didn’t really work (kept throwing server errors) and TBH I’ve dealt with Jack enough for this lifetime.

Flatpak labels it as master because while Flathub’s default is ‘stable’, on normal machines it’s ‘master’, and since it isn’t set in the manifest different values are used. It’s actually pretty neat because this way I can install a local build of MuseScore beside the Flathub version, without having to change the manifest, and run whichever one I want.

BTW, you needn’t use `sudo` with Flatpak – for a local copy use `--user`, otherwise it’ll ask you for a password via Polkit.

Hm, though I wish someone would get PortMidi’s build system up to shape, it’s quite a pain having to deal with all that Java stuff just to remove it after the build.

Thanks again for all the help!

**Pull request merged**
