### PR TITLE
KDE 5.12

### PR DESCRIPTION
**Pull request by jurf**

### CODE REVIEW

**Comment by jurf** [comment]
bot, build

**Comment by eszlari** [comment]
qtwebkit is only built for x86_64 and aarch64 atm:

https://github.com/flathub/io.qt.qtwebkit.BaseApp/commit/3001f8d4a0c670610bc8b052cda102eb47bfa962

**Comment by jurf** [comment]
I know, but it should be only temporary: https://github.com/flathub/io.qt.qtwebkit.BaseApp/pull/15

**Comment by jurf** [comment]
Superseded by #32.

**Pull request closed without merging**
