### PR TITLE
Cleanup

### PR DESCRIPTION
**Pull request by jurf**
And a bunch of other things. Just want to give it a test drive before deploying it.

### CODE REVIEW

**Comment by jurf** [comment]
bot, build

**Comment by jurf** [comment]
bot, build

**Comment by eszlari** [comment]
If add `--env=TMPDIR=$XDG_CACHE_HOME` to `finish-args`, you can get a ride of the extra script.

**Comment by jurf** [comment]
> If you add `--env=TMPDIR=$XDG_CACHE_HOME` to `finish-args`, you can get a rid of the extra script.

Been there, done that, it literally set it to `$XDG_CACHE_HOME`. At least it was the case when I wrote that bit, I remember other packages using the same scheme.

Didn’t know about that launchable thing though, cheers. Can I remove that from the AppData PR on upstream MuseScore too?

**Comment by jurf** [comment]
Yeah:

```
$ echo $TMPDIR
$XDG_CACHE_HOME
```

**Comment by jurf** [comment]
bot, build

**Comment by jurf** [comment]
@eszlari:

From [App Requirements](https://github.com/flathub/flathub/wiki/App-Requirements):

> If an application uses `$TMPDIR` to contain lock files or shared files with other process create a wrapper script that sets it to `$XDG_CACHE_HOME`.

**Comment by eszlari** [comment]
http://docs.flatpak.org/en/latest/sandbox-permissions.html
> If an application uses $TMPDIR to contain lock files or shared files with other processes, you may want to add --env=TMPDIR=/var/tmp.

**Comment by TingPing** [comment]
They solve two different problems. `/var/tmp` is great for sharing with yourself (lock files), `$XDG_CACHE_HOME` is great for sharing outside of the sandbox.

**Comment by jurf** [comment]
bot, build

**Pull request merged**
